# Explore here

In [22]:
#Importar librerias
import pandas as pd
import numpy as np


region	price	year	manufacturer	model	condition	cylinders	fuel	odometer	transmission	drive	size	type	paint_color	description	state

In [23]:
#Cargar datos

#Dataset grande 1
df = pd.read_csv('../data/vehicles.csv', usecols=['region', 'price', 'year','manufacturer','model','condition','cylinders','fuel','odometer','transmission','drive','size','type','paint_color','description','state']) #cargar solo las columnas necesarias

#Dataset datos Ecuador - ignorar Ecuador
#df_ec=pd.read_csv('../data/patiotuerca2023-02-10.csv')

#Dataset 90000 cars 
#df_90k=pd.read_csv('../data/CarsData.csv')



In [8]:
#Explorar datos Dataset grande 1
df.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   region        426880 non-null  object 
 1   price         426880 non-null  int64  
 2   year          425675 non-null  float64
 3   manufacturer  409234 non-null  object 
 4   model         421603 non-null  object 
 5   condition     252776 non-null  object 
 6   cylinders     249202 non-null  object 
 7   fuel          423867 non-null  object 
 8   odometer      422480 non-null  float64
 9   transmission  424324 non-null  object 
 10  drive         296313 non-null  object 
 11  size          120519 non-null  object 
 12  type          334022 non-null  object 
 13  paint_color   296677 non-null  object 
 14  description   426810 non-null  object 
 15  state         426880 non-null  object 
dtypes: float64(2), int64(1), object(13)
memory usage: 52.1+ MB


In [24]:
df.head()


region  price  year manufacturer model condition cylinders  \
0                prescott   6000   NaN          NaN   NaN       NaN       NaN   
1            fayetteville  11900   NaN          NaN   NaN       NaN       NaN   
2            florida keys  21000   NaN          NaN   NaN       NaN       NaN   
3  worcester / central MA   1500   NaN          NaN   NaN       NaN       NaN   
4              greensboro   4900   NaN          NaN   NaN       NaN       NaN   

  fuel  odometer transmission drive size type paint_color description state  
0  NaN       NaN          NaN   NaN  NaN  NaN         NaN         NaN    az  
1  NaN       NaN          NaN   NaN  NaN  NaN         NaN         NaN    ar  
2  NaN       NaN          NaN   NaN  NaN  NaN         NaN         NaN    fl  
3  NaN       NaN          NaN   NaN  NaN  NaN         NaN         NaN    ma  
4  NaN       NaN          NaN   NaN  NaN  NaN         NaN         NaN    nc

In [25]:
df.drop(columns=['description','condition'],inplace=True)





In [32]:
pd.set_option('display.max_columns', None)
df['year'].fillna(0, inplace=True)
df['year'] = df['year'].astype(int)

df.sample(10)



C:\Users\Juan\AppData\Local\Temp\ipykernel_17204\2917567633.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['year'].fillna(0, inplace=True)


region  price  year   manufacturer  \
281405                 syracuse   9995  2012            gmc   
57307           san luis obispo  13995  2002         toyota   
92548             daytona beach  11700  2009  mercedes-benz   
126442             northwest GA  24995  2012           ford   
73427          colorado springs   2500  1991         nissan   
366146                   austin  24590  2019         nissan   
136281  spokane / coeur d'alene   7495  2006         subaru   
248129                las vegas  31987  2019           jeep   
95158     ft myers / SW florida  35590  2017           ford   
295222                 columbus   6995  2008          buick   

                         model    cylinders fuel  odometer transmission drive  \
281405              acadia awd  6 cylinders  gas  129780.0    automatic   4wd   
57307              4runner sr5  6 cylinders  gas  109443.0    automatic   rwd   
92548                   cls550  8 cylinders  gas  104737.0    automatic   rwd   
126442      f250 xl super duty          NaN  gas   52377.0    automatic   NaN   
73427                 hardbody  4 cylinders  gas  174000.0    automatic   rwd   
366146     frontier king cab s          NaN  gas   13225.0        other   fwd   
136281           impreza wagon  4 cylinders  gas  146079.0    automatic   4wd   
248129                cherokee  6 cylinders  gas   13349.0    automatic   4wd   
95158   f150 supercrew cab xlt  6 cylinders  gas   36536.0        other   NaN   
295222            lacrosse cxl  6 cylinders  gas   77000.0    automatic   fwd   

             size    type paint_color state  
281405        NaN     NaN         NaN    ny  
57307    mid-size     SUV         NaN    ca  
92548   full-size   sedan       black    fl  
126442        NaN     NaN        grey    ga  
73427         NaN  pickup         red    co  
366146        NaN  pickup       white    tx  
136281        NaN   wagon        blue    id  
248129    compact     SUV      custom    nv  
95158         NaN  pickup      silver    fl  
295222   mid-size   sedan        blue    oh

In [17]:
df['size'].unique()


array([nan, 'full-size', 'mid-size', 'compact', 'sub-compact'],
      dtype=object)

In [18]:
df['type'].unique()


array([nan, 'pickup', 'truck', 'other', 'coupe', 'SUV', 'hatchback',
       'mini-van', 'sedan', 'offroad', 'bus', 'van', 'convertible',
       'wagon'], dtype=object)

In [19]:
unique_combinations = [tuple(row) for row in df[['size', 'type']].drop_duplicates().values]
print(unique_combinations)


[(nan, nan), (nan, 'pickup'), ('full-size', 'truck'), (nan, 'truck'), (nan, 'other'), (nan, 'coupe'), ('full-size', 'SUV'), (nan, 'SUV'), (nan, 'hatchback'), ('full-size', 'pickup'), ('full-size', 'mini-van'), ('mid-size', 'sedan'), (nan, 'sedan'), ('mid-size', 'mini-van'), ('full-size', 'offroad'), ('full-size', 'bus'), ('full-size', 'van'), ('mid-size', 'SUV'), ('compact', 'sedan'), (nan, 'convertible'), ('compact', 'convertible'), (nan, 'wagon'), ('full-size', 'sedan'), ('mid-size', 'convertible'), ('mid-size', 'coupe'), ('mid-size', 'hatchback'), (nan, 'van'), ('mid-size', 'truck'), ('full-size', 'coupe'), ('compact', 'hatchback'), ('mid-size', 'wagon'), ('full-size', 'wagon'), ('compact', 'SUV'), ('compact', nan), ('compact', 'coupe'), ('sub-compact', 'other'), ('mid-size', 'van'), ('mid-size', nan), (nan, 'bus'), ('full-size', nan), ('mid-size', 'pickup'), ('compact', 'truck'), ('full-size', 'other'), ('full-size', 'convertible'), ('compact', 'other'), (nan, 'mini-van'), ('sub-co

In [21]:
# To show all rows
pd.set_option('display.max_rows', None)

# To show all columns
pd.set_option('display.max_columns', None)

# Then, run your code again
df[['size', 'type']].drop_duplicates()

size         type
0               NaN          NaN
27              NaN       pickup
31        full-size        truck
34              NaN        truck
36              NaN        other
42              NaN        coupe
46        full-size          SUV
49              NaN          SUV
54              NaN    hatchback
55        full-size       pickup
59        full-size     mini-van
73         mid-size        sedan
75              NaN        sedan
86         mid-size     mini-van
119       full-size      offroad
122       full-size          bus
126       full-size          van
138        mid-size          SUV
160         compact        sedan
172             NaN  convertible
186         compact  convertible
223             NaN        wagon
224       full-size        sedan
245        mid-size  convertible
264        mid-size        coupe
270        mid-size    hatchback
279             NaN          van
332        mid-size        truck
338       full-size        coupe
370         compact    hatchback
373        mid-size        wagon
415       full-size        wagon
440         compact          SUV
458         compact          NaN
494         compact        coupe
564     sub-compact        other
735        mid-size          van
799        mid-size          NaN
815             NaN          bus
864       full-size          NaN
945        mid-size       pickup
1012        compact        truck
1132      full-size        other
1203      full-size  convertible
1447        compact        other
1845            NaN     mini-van
2243    sub-compact          SUV
2425    sub-compact        truck
2645    sub-compact  convertible
2918      full-size    hatchback
3233        compact        wagon
3396    sub-compact          NaN
3467            NaN      offroad
3721    sub-compact    hatchback
3880        compact       pickup
3927    sub-compact        coupe
3942        compact     mini-van
4127    sub-compact        sedan
4825        compact      offroad
4890       mid-size        other
5191       mid-size      offroad
5240    sub-compact        wagon
9150        compact          van
9183    sub-compact       pickup
10417      mid-size          bus
12380   sub-compact     mini-van
13263   sub-compact      offroad
147587  sub-compact          van
210280      compact          bus
329343  sub-compact          bus

In [27]:
df.manufacturer.unique()


array([nan, 'gmc', 'chevrolet', 'toyota', 'ford', 'jeep', 'nissan', 'ram',
       'mazda', 'cadillac', 'honda', 'dodge', 'lexus', 'jaguar', 'buick',
       'chrysler', 'volvo', 'audi', 'infiniti', 'lincoln', 'alfa-romeo',
       'subaru', 'acura', 'hyundai', 'mercedes-benz', 'bmw', 'mitsubishi',
       'volkswagen', 'porsche', 'kia', 'rover', 'ferrari', 'mini',
       'pontiac', 'fiat', 'tesla', 'saturn', 'mercury', 'harley-davidson',
       'datsun', 'aston-martin', 'land rover', 'morgan'], dtype=object)

In [44]:
df.model.unique()


array([nan, 'sierra 1500 crew cab slt', 'silverado 1500', ...,
       'gand wagoneer', '96 Suburban', 'Paige Glenbrook Touring'],
      shape=(29668,), dtype=object)

In [47]:
df[df.manufacturer=='toyota']['model'].unique()


array(['tundra double cab sr', 'tacoma', 'tacoma access cab pickup', ...,
       'tundra sr5 sr5 4dr double cab', 'prius prime advantage',
       'corolla le 1.8l'], shape=(1722,), dtype=object)

In [29]:
#funcion para juntar datasets  
#df['year']=df['year'].astype('int64')

In [30]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   region        426880 non-null  object 
 1   price         426880 non-null  int64  
 2   year          426880 non-null  int64  
 3   manufacturer  409234 non-null  object 
 4   model         421603 non-null  object 
 5   cylinders     249202 non-null  object 
 6   fuel          423867 non-null  object 
 7   odometer      422480 non-null  float64
 8   transmission  424324 non-null  object 
 9   drive         296313 non-null  object 
 10  size          120519 non-null  object 
 11  type          334022 non-null  object 
 12  paint_color   296677 non-null  object 
 13  state         426880 non-null  object 
dtypes: float64(1), int64(2), object(11)
memory usage: 45.6+ MB


In [31]:
df.head()


region  price  year manufacturer model cylinders fuel  \
0                prescott   6000     0          NaN   NaN       NaN  NaN   
1            fayetteville  11900     0          NaN   NaN       NaN  NaN   
2            florida keys  21000     0          NaN   NaN       NaN  NaN   
3  worcester / central MA   1500     0          NaN   NaN       NaN  NaN   
4              greensboro   4900     0          NaN   NaN       NaN  NaN   

   odometer transmission drive size type paint_color state  
0       NaN          NaN   NaN  NaN  NaN         NaN    az  
1       NaN          NaN   NaN  NaN  NaN         NaN    ar  
2       NaN          NaN   NaN  NaN  NaN         NaN    fl  
3       NaN          NaN   NaN  NaN  NaN         NaN    ma  
4       NaN          NaN   NaN  NaN  NaN         NaN    nc

De la DF 90k, podemos agregar la columna de "engineSize" y "mpg" ya que en el DF1 solo esta el cilindraje y "mpg" podemos cambiarlo a "km/l"

df & df_90k

In [29]:
df_90k_p2=df_90k[['model','year','Manufacturer','engineSize','mpg']]


In [30]:

df_merged=pd.merge(df,df_90k_p2, how='left', left_on=['model','year','manufacturer'], right_on=['model','year','Manufacturer'])


In [31]:
df_merged.head()



region  price  year manufacturer model condition cylinders  \
0                prescott   6000  <NA>          NaN   NaN       NaN       NaN   
1            fayetteville  11900  <NA>          NaN   NaN       NaN       NaN   
2            florida keys  21000  <NA>          NaN   NaN       NaN       NaN   
3  worcester / central MA   1500  <NA>          NaN   NaN       NaN       NaN   
4              greensboro   4900  <NA>          NaN   NaN       NaN       NaN   

  fuel  odometer title_status transmission drive size type paint_color  \
0  NaN       NaN          NaN          NaN   NaN  NaN  NaN         NaN   
1  NaN       NaN          NaN          NaN   NaN  NaN  NaN         NaN   
2  NaN       NaN          NaN          NaN   NaN  NaN  NaN         NaN   
3  NaN       NaN          NaN          NaN   NaN  NaN  NaN         NaN   
4  NaN       NaN          NaN          NaN   NaN  NaN  NaN         NaN   

  description state  lat  long Manufacturer  engineSize  mpg  
0         NaN    az  NaN   NaN          NaN         NaN  NaN  
1         NaN    ar  NaN   NaN          NaN         NaN  NaN  
2         NaN    fl  NaN   NaN          NaN         NaN  NaN  
3         NaN    ma  NaN   NaN          NaN         NaN  NaN  
4         NaN    nc  NaN   NaN          NaN         NaN  NaN

In [32]:

df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 22 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   region        426880 non-null  object 
 1   price         426880 non-null  int64  
 2   year          425675 non-null  Int64  
 3   manufacturer  409234 non-null  object 
 4   model         421603 non-null  object 
 5   condition     252776 non-null  object 
 6   cylinders     249202 non-null  object 
 7   fuel          423867 non-null  object 
 8   odometer      422480 non-null  float64
 9   title_status  418638 non-null  object 
 10  transmission  424324 non-null  object 
 11  drive         296313 non-null  object 
 12  size          120519 non-null  object 
 13  type          334022 non-null  object 
 14  paint_color   296677 non-null  object 
 15  description   426810 non-null  object 
 16  state         426880 non-null  object 
 17  lat           420331 non-null  float64
 18  long